/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.clinica.view;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;

/**
 *
 * @author nneto
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        URL caminhoIcone = getClass().getResource("/br/com/clinica/imagens/logo.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitulo);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_inicio = new javax.swing.JMenu();
        jmi_pacientes = new javax.swing.JMenuItem();
        jmi_medicos = new javax.swing.JMenuItem();
        jmi_procedimentos = new javax.swing.JMenuItem();
        jmi_prescricoes = new javax.swing.JMenuItem();
        jmi_consultas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clínica Médica");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/clinica/imagens/unnamed (1).png"))); // NOI18N

        jm_inicio.setText("Inicio");

        jmi_pacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/clinica/imagens/paciente.png"))); // NOI18N
        jmi_pacientes.setText("Pacientes");
        jmi_pacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_pacientesActionPerformed(evt);
            }
        });
        jm_inicio.add(jmi_pacientes);

        jmi_medicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/clinica/imagens/medico.png"))); // NOI18N
        jmi_medicos.setText("Médicos");
        jmi_medicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_medicosActionPerformed(evt);
            }
        });
        jm_inicio.add(jmi_medicos);

        jmi_procedimentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/clinica/imagens/procedimentos.png"))); // NOI18N
        jmi_procedimentos.setText("Procedimentos");
        jmi_procedimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_procedimentosActionPerformed(evt);
            }
        });
        jm_inicio.add(jmi_procedimentos);

        jmi_prescricoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/clinica/imagens/relatorios.png"))); // NOI18N
        jmi_prescricoes.setText("Prescrições");
        jmi_prescricoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_prescricoesActionPerformed(evt);
            }
        });
        jm_inicio.add(jmi_prescricoes);

        jmi_consultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/clinica/imagens/consultas.png"))); // NOI18N
        jmi_consultas.setText("Consultas");
        jmi_consultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_consultasActionPerformed(evt);
            }
        });
        jm_inicio.add(jmi_consultas);

        jMenuBar1.add(jm_inicio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(141, 141, 141))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_pacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_pacientesActionPerformed
        PacienteView pacienteView = new PacienteView();
        pacienteView.setVisible(true);
    }//GEN-LAST:event_jmi_pacientesActionPerformed

    private void jmi_medicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_medicosActionPerformed
        MedicoView medicoView = new MedicoView();
        medicoView.setVisible(true);
    }//GEN-LAST:event_jmi_medicosActionPerformed

    private void jmi_procedimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_procedimentosActionPerformed
        ProcedimentoView procedimentoView = new ProcedimentoView();
        procedimentoView.setVisible(true);
    }//GEN-LAST:event_jmi_procedimentosActionPerformed

    private void jmi_prescricoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_prescricoesActionPerformed
        PrescricaoView prescricaoView = new PrescricaoView();
        prescricaoView.setVisible(true);
    }//GEN-LAST:event_jmi_prescricoesActionPerformed

    private void jmi_consultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_consultasActionPerformed
        ConsultaView consultaView = new ConsultaView();
        consultaView.setVisible(true);
    }//GEN-LAST:event_jmi_consultasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jm_inicio;
    private javax.swing.JMenuItem jmi_consultas;
    private javax.swing.JMenuItem jmi_medicos;
    private javax.swing.JMenuItem jmi_pacientes;
    private javax.swing.JMenuItem jmi_prescricoes;
    private javax.swing.JMenuItem jmi_procedimentos;
    // End of variables declaration//GEN-END:variables

}
